### PR TITLE
Detailed fitting

### PR DESCRIPTION
**Pull request by KalleLeppala**
The fitting function now deals with the admix and the edge variables separately. For this reason, access to the fitted data is destroyed as the environments and such were confusing me; the fit function just returns a list of all the info you could possibly need. In the beginning of fit.R there's some comments with my suggestions and remarks. The fit function is about twice as slow as it easily could be and I'll fix that in a while, but I just thought it's about time for an update now.

### CODE REVIEW

**Comment by mailund** [comment]
Great! Will look it as soon as I can

On 15 Sep 2015, at 16:43, KalleLeppala <notifications@github.com<mailto:notifications@github.com>> wrote:

The fitting function now deals with the admix and the edge variables separately. For this reason, access to the fitted data is destroyed as the environments and such were confusing me; the fit function just returns a list of all the info you could possibly need. In the beginning of fit.R there's some comments with my suggestions and remarks. The fit function is about twice as slow as it easily could be and I'll fix that in a while, but I just thought it's about time for an update now.

---

You can view, comment on, or merge this pull request online at:

  https://github.com/mailund/admixture_graph/pull/6

Commit Summary
-   Committing a useless comment line.
-   Detailed fitting

File Changes
-   A .RDatahttps://github.com/mailund/admixture_graph/pull/6/files#diff-0 (0)
-   M R/fitting.Rhttps://github.com/mailund/admixture_graph/pull/6/files#diff-1 (194)
-   M README-fitted_data-1.pnghttps://github.com/mailund/admixture_graph/pull/6/files#diff-2 (0)
-   M README-graph-1.pnghttps://github.com/mailund/admixture_graph/pull/6/files#diff-3 (0)
-   M README.mdhttps://github.com/mailund/admixture_graph/pull/6/files#diff-4 (60)

Patch Links:
-   https://github.com/mailund/admixture_graph/pull/6.patch
-   https://github.com/mailund/admixture_graph/pull/6.diff

**Comment by KalleLeppala** [comment]
Oh by the way, I see that the bear example in readme has new admix variables, so when I comment the bears I mean the 2 variable version.

**Comment by KalleLeppala** [comment]
I'm closing this because I can't make another pull request for some reason and I suspect this existing is a potential reason.

**Comment by KalleLeppala** [comment]
Actually I see the new changes have something to do with this request, so reopen and investigate.

**Comment by mailund** [comment]
This request is now on a separate branch in my version of the package. I'll check it in more details and then merge it in.

**Pull request closed without merging**
